### ISSUE TITLE
Incorrect command in documentation of 'RegisterContextMenuToBackground'

### ISSUE THREAD

**Issue by DineshSolanki** [ghost1372/ghost1372.github.io#33]
currently, the command is - 
```csharp
string command = $"\"{Process.GetCurrentProcess().MainModule.FileName}\" \"%1\"";
ApplicationHelper.RegisterContextMenuToBackground("MyApp", command);
```
while the %1 should be %V in this case for background context action to work.

```csharp
string command = $"\"{Process.GetCurrentProcess().MainModule.FileName}\" \"%V\"";
ApplicationHelper.RegisterContextMenuToBackground("MyApp", command);
```

**Comment by ghost1372** [comment]
for HandySub app, i used this code and everythings worked fine, also this is just an example we dont expect to work in real app😅

**Comment by DineshSolanki** [comment]
> 
> 
> for HandySub app, I used this code and everything worked fine, also this is just an example we don't expect to work in a real app😅


Of course, I'm not talking about the whole code, I'm talking about the parameter.

%1 – The first file parameter. which is directory path (when right-clicking on any folder, which is why it's used for directory context command)
%v – For verbs that are none implies all. If there is no parameter passed this is the working directory. (which is why it is used for background context command)

[MSDN](https://web.archive.org/web/20111002101214/http://msdn.microsoft.com/en-us/library/windows/desktop/cc144101(v=vs.85).aspx)
